services:
  # Gateway Service (Main Backend)
  - type: web
    name: satellite-tracking-gateway
    runtime: node
    plan: standard
    region: oregon
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        fromDatabase:
          name: satellite-db
          property: connectionString
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CESIUM_ION_TOKEN
        sync: false
      - key: AUTO_TOKEN_ROTATION
        value: true
      - key: SELF_HEALING_ENABLED
        value: true
      - key: THREAT_ANALYSIS_ENABLED
        value: true
      - key: ORBIT_SERVICE_URL
        value: http://satellite-orbit-service:5000
    healthCheckPath: /api/health
    domains:
      - satellite-tracking.onrender.com
    buildFilter:
      paths:
        - backend/**
      ignoredPaths:
        - README.md
        - docs/**

  # Orbit Microservice (Python)
  - type: web
    name: satellite-orbit-service
    runtime: python
    plan: pro
    region: oregon
    buildCommand: cd orbit-service && pip install -r requirements.txt
    startCommand: cd orbit-service && gunicorn --bind 0.0.0.0:$PORT --workers 4 --worker-class gevent --timeout 120 app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: REDIS_URL
        sync: false
      - key: CELESTRAK_API_BASE
        value: https://celestrak.org
      - key: AUTO_TOKEN_ROTATION
        value: true
      - key: THREAT_ANALYSIS_ENABLED
        value: true
      - key: MAX_SATELLITES_RENDER
        value: 20000
    healthCheckPath: /health
    buildFilter:
      paths:
        - orbit-service/**
      ignoredPaths:
        - README.md
        - tests/**

  # Frontend (React) - Static site without region
  - type: web
    name: satellite-tracking-frontend
    runtime: static
    plan: starter
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/build
    pullRequestPreviewsEnabled: false
    domains:
      - app.satellite-tracking.com
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cesium.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://cesium.com; img-src 'self' data: https: blob:; connect-src 'self' https://api.cesium.com https://assets.ion.cesium.com wss: ws:; worker-src 'self' blob:; font-src 'self' https:;"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    buildFilter:
      paths:
        - frontend/**
      ignoredPaths:
        - README.md
        - tests/**

  # Static Portfolio Site - Without region
  - type: web
    name: ruddro-portfolio
    runtime: starter
    plan: Free static
    buildCommand: cd static-site && echo "No build required"
    staticPublishPath: static-site
    pullRequestPreviewsEnabled: false
    domains:
      - portfolio.ruddro.com
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    buildFilter:
      paths:
        - static-site/**

  # Background Worker - Data Processor
  - type: worker
    name: satellite-data-processor
    runtime: python
    plan: standard
    region: oregon
    buildCommand: cd orbit-service && pip install -r requirements.txt
    startCommand: cd orbit-service && python worker.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: REDIS_URL
        sync: false
      - key: CELESTRAK_API_BASE
        value: https://celestrak.org
      - key: WORKER_TYPE
        value: data_processor
    buildFilter:
      paths:
        - orbit-service/**

  # Background Worker - Threat Analyzer
  - type: worker
    name: threat-analyzer
    runtime: python
    plan: standard
    region: oregon
    buildCommand: cd orbit-service && pip install -r requirements.txt
    startCommand: cd orbit-service && python threat_worker.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: REDIS_URL
        sync: false
      - key: CELESTRAK_API_BASE
        value: https://celestrak.org
      - key: WORKER_TYPE
        value: threat_analyzer
      - key: THREAT_ANALYSIS_ENABLED
        value: true
    buildFilter:
      paths:
        - orbit-service/**

  # Cron Job - Satellite Data Sync
  - type: cron
    name: satellite-data-sync
    runtime: python
    schedule: "*/15 * * * *"  # Every 15 minutes
    buildCommand: cd orbit-service && pip install -r requirements.txt
    startCommand: cd orbit-service && python sync_satellites.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: REDIS_URL
        sync: false
      - key: CELESTRAK_API_BASE
        value: https://celestrak.org
    buildFilter:
      paths:
        - orbit-service/**

  # Cron Job - Threat Assessment Batch
  - type: cron
    name: threat-assessment-batch
    runtime: python
    schedule: "0 */6 * * *"  # Every 6 hours
    buildCommand: cd orbit-service && pip install -r requirements.txt
    startCommand: cd orbit-service && python batch_threat_analysis.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: REDIS_URL
        sync: false
      - key: THREAT_ANALYSIS_ENABLED
        value: true
    buildFilter:
      paths:
        - orbit-service/**

# Databases
databases:
  - name: satellite-db
    databaseName: satellite_tracker
    user: satellite_user
    plan: standard
    region: oregon
