name: deploy-static
on:
  push:
    branches: [main]
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sed -i "s/PASTE_YOUR_CESIUM_ION_TOKEN_HERE/${{ secrets.CESIUM_ION_TOKEN }}/" public/app.js
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
